### ISSUE TITLE
Clicking on 'x' to remove a single entry doesn't clear / refresh the search pane with the previous searches

### ISSUE THREAD

**Issue by VorTechS** [coderobe/unbreak-tweetdeck#1]
![unbreaktweetdeckbreaksit](https://cloud.githubusercontent.com/assets/516350/24649326/9bd8d98c-191e-11e7-94e5-5108de782859.png)

If you click to remove a single item from the search history, the action 'executes' but the search history does not refresh to remove the item, as it would normally.  However, if you fire up another tab, and re-click the search, the item you clicked to remove has disappeared.

**Comment by coderobe** [comment]
i'll look into it, thanks for the feedback!

**Comment by coderobe** [comment]
i can't seem to reproduce it - removing entries from my recent searches works just fine & updates live - are you loading any other userscripts that may clash with this?

**Comment by VorTechS** [comment]
Okay, I'll have a look my end, see if any of my own code injection is causing problems ... or if TrendScript might be the culprit.

**Comment by VorTechS** [comment]
Removed all code injection, and the bug is still there.  Looks like it's a TweetDeck bug when used with Chromium.  Thanks for looking at it though!
